function ErrMsg( I )
% Displays error messages.

%% prepare error message
if strcmp(I,'RobustCoPlot:DataColNums')
    Msg = [...
        'Input of the function should be a structure with DataColNums field,\n' ...
        'each possible value of which should be less than the number of variables\n' ...
        'defined in data file.' ...
        ];
end
if strcmp(I,'RobustCoPlot:StdType') || strcmp(I,'GenerateDisSimilarity:StdType')
    Msg = [...
        'Input of the function should be a structure with ''StdType'' field,\n' ...
        'possible value of which can be ''Mean'' or ''Median''.' ...
        ];
end
%% prepare a format for error messages
FormattedMsg=['\n' I '\n' Msg];
error(I,FormattedMsg);
end